//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_CLINICAEntities : DbContext
    {
        public DB_CLINICAEntities()
            : base("name=DB_CLINICAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<GS_ASEGURADORA> GS_ASEGURADORA { get; set; }
        public virtual DbSet<GS_ASEGURADORA_PERIODO> GS_ASEGURADORA_PERIODO { get; set; }
        public virtual DbSet<GS_ATENCION> GS_ATENCION { get; set; }
        public virtual DbSet<GS_DETALLE_ATENCION> GS_DETALLE_ATENCION { get; set; }
        public virtual DbSet<GS_Especialidad> GS_Especialidad { get; set; }
        public virtual DbSet<GS_MEDICO> GS_MEDICO { get; set; }
        public virtual DbSet<GS_ORDEN_MEDICA> GS_ORDEN_MEDICA { get; set; }
        public virtual DbSet<GS_ORDEN_PROCEDIMIENTO> GS_ORDEN_PROCEDIMIENTO { get; set; }
        public virtual DbSet<GS_PACIENTE> GS_PACIENTE { get; set; }
        public virtual DbSet<GS_PERIODO> GS_PERIODO { get; set; }
        public virtual DbSet<GS_PROCEDIMIENTO> GS_PROCEDIMIENTO { get; set; }
        public virtual DbSet<GS_SRS> GS_SRS { get; set; }
        public virtual DbSet<GS_SRS_PROCEDIMIENTO> GS_SRS_PROCEDIMIENTO { get; set; }
        public virtual DbSet<GS_TIPO_TRAMA> GS_TIPO_TRAMA { get; set; }
        public virtual DbSet<GS_TRAMA> GS_TRAMA { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_GENERAR_SRS(Nullable<int> iDOrdenMedica, Nullable<int> iDAseguradora)
        {
            var iDOrdenMedicaParameter = iDOrdenMedica.HasValue ?
                new ObjectParameter("IDOrdenMedica", iDOrdenMedica) :
                new ObjectParameter("IDOrdenMedica", typeof(int));
    
            var iDAseguradoraParameter = iDAseguradora.HasValue ?
                new ObjectParameter("IDAseguradora", iDAseguradora) :
                new ObjectParameter("IDAseguradora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GENERAR_SRS", iDOrdenMedicaParameter, iDAseguradoraParameter);
        }
    
        public virtual ObjectResult<string> SP_GENERAR_TRAMAS_PDF(Nullable<int> idPeriodo, Nullable<int> idAseguradora, string observacion, string usuario)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("IdPeriodo", idPeriodo) :
                new ObjectParameter("IdPeriodo", typeof(int));
    
            var idAseguradoraParameter = idAseguradora.HasValue ?
                new ObjectParameter("IdAseguradora", idAseguradora) :
                new ObjectParameter("IdAseguradora", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GENERAR_TRAMAS_PDF", idPeriodoParameter, idAseguradoraParameter, observacionParameter, usuarioParameter);
        }
    
        public virtual int sql2pdf(string filename)
        {
            var filenameParameter = filename != null ?
                new ObjectParameter("filename", filename) :
                new ObjectParameter("filename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sql2pdf", filenameParameter);
        }
    
        public virtual ObjectResult<string> SP_GENERAR_PDF_ASEGURADORA(Nullable<int> id_SRS)
        {
            var id_SRSParameter = id_SRS.HasValue ?
                new ObjectParameter("Id_SRS", id_SRS) :
                new ObjectParameter("Id_SRS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GENERAR_PDF_ASEGURADORA", id_SRSParameter);
        }
    
        public virtual ObjectResult<listPeriodosByAseguradaId_Result> listPeriodosByAseguradaId(Nullable<int> idAseguradora)
        {
            var idAseguradoraParameter = idAseguradora.HasValue ?
                new ObjectParameter("IdAseguradora", idAseguradora) :
                new ObjectParameter("IdAseguradora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listPeriodosByAseguradaId_Result>("listPeriodosByAseguradaId", idAseguradoraParameter);
        }
    }
}
