//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.GS_MEDICO = new HashSet<GS_MEDICO>();
        }
    
        public int IDEmpleado { get; set; }
        public string NombreEmp { get; set; }
        public string Ap_paterno { get; set; }
        public string Ap_materno { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GS_MEDICO> GS_MEDICO { get; set; }
    }
}
