//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_ATENCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GS_ATENCION()
        {
            this.GS_DETALLE_ATENCION = new HashSet<GS_DETALLE_ATENCION>();
            this.GS_ORDEN_MEDICA = new HashSet<GS_ORDEN_MEDICA>();
        }
    
        public int IDAtencion { get; set; }
        public int IDPaciente { get; set; }
        public int IDMedico { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
        public Nullable<int> IDAseguradora { get; set; }
    
        public virtual GS_ASEGURADORA GS_ASEGURADORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GS_DETALLE_ATENCION> GS_DETALLE_ATENCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GS_ORDEN_MEDICA> GS_ORDEN_MEDICA { get; set; }
        public virtual GS_MEDICO GS_MEDICO { get; set; }
        public virtual GS_PACIENTE GS_PACIENTE { get; set; }
    }
}
