//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_ASEGURADORA_PERIODO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GS_ASEGURADORA_PERIODO()
        {
            this.GS_TRAMA = new HashSet<GS_TRAMA>();
        }
    
        public int IDAseguradora { get; set; }
        public int IDPeriodo { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
    
        public virtual GS_ASEGURADORA GS_ASEGURADORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GS_TRAMA> GS_TRAMA { get; set; }
        public virtual GS_PERIODO GS_PERIODO { get; set; }
    }
}
