//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_DETALLE_ATENCION
    {
        public int IDAtencion { get; set; }
        public int Linea { get; set; }
        public string Descripcion { get; set; }
    
        public virtual GS_ATENCION GS_ATENCION { get; set; }
    }
}
