//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_MEDICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GS_MEDICO()
        {
            this.GS_ATENCION = new HashSet<GS_ATENCION>();
        }
    
        public int IDMedico { get; set; }
        public int IDEspecialidad { get; set; }
        public string NroCMP { get; set; }
        public Nullable<int> IDEmpleado { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GS_ATENCION> GS_ATENCION { get; set; }
        public virtual GS_Especialidad GS_Especialidad { get; set; }
    }
}
