//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_ORDEN_PROCEDIMIENTO
    {
        public int IDProcedimiento { get; set; }
        public int IDOrdenMedica { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
    
        public virtual GS_ORDEN_MEDICA GS_ORDEN_MEDICA { get; set; }
        public virtual GS_PROCEDIMIENTO GS_PROCEDIMIENTO { get; set; }
    }
}
