//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_PROCEDIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GS_PROCEDIMIENTO()
        {
            this.GS_ORDEN_PROCEDIMIENTO = new HashSet<GS_ORDEN_PROCEDIMIENTO>();
            this.GS_SRS_PROCEDIMIENTO = new HashSet<GS_SRS_PROCEDIMIENTO>();
        }
    
        public int IDProcedimiento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GS_ORDEN_PROCEDIMIENTO> GS_ORDEN_PROCEDIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GS_SRS_PROCEDIMIENTO> GS_SRS_PROCEDIMIENTO { get; set; }
    }
}
