//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_SRS_PROCEDIMIENTO
    {
        public int IDProcedimiento { get; set; }
        public int IDSRS { get; set; }
        public string Estado { get; set; }
        public string Ruta { get; set; }
        public string Codigo_requerimiento { get; set; }
    
        public virtual GS_PROCEDIMIENTO GS_PROCEDIMIENTO { get; set; }
        public virtual GS_SRS GS_SRS { get; set; }
    }
}
