//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DattatecPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS_TRAMA
    {
        public int IDTrama { get; set; }
        public int IDTipo { get; set; }
        public int IDAseguradora { get; set; }
        public int IDPeriodo { get; set; }
        public string Ruta { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
        public string Usuario { get; set; }
    
        public virtual GS_ASEGURADORA_PERIODO GS_ASEGURADORA_PERIODO { get; set; }
        public virtual GS_TIPO_TRAMA GS_TIPO_TRAMA { get; set; }
    }
}
